version: '3.7'

x-env-postgres: &env-postgres
  POSTGRES_DB: teststudio_lite_db
  POSTGRES_USER: teststudio_lite_db_user
  POSTGRES_PASSWORD: iqb_tba_db_password_1


x-env-initdata: &env-initdata
  SUPERUSER_NAME: super
  SUPERUSER_PASSWORD: user123

services:
  teststudio-lite-db:
    build:
      context: teststudio-lite-db-postgres
    container_name: teststudio-lite-db-postgres
    environment:
      <<: *env-postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "9097:5432"

  teststudio-lite-backend:
    build:
      context: teststudio-lite-backend
    container_name: teststudio-lite-backend
    environment:
      <<: *env-postgres
      <<: *env-initdata
      POSTGRES_HOST: teststudio-lite-db
      POSTGRES_PORT: 5432
    depends_on:
      - teststudio-lite-db
    volumes:
      - ./teststudio-lite-backend/src/:/var/www/html/
      - ./data/itemplayers:/var/www/html/itemplayers
      - ./data/itemauthoringtools:/var/www/html/itemauthoringtools
#      - ./teststudio-lite-backend/data:/var/www/html/vo_data
    ports:
      - "9095:80"
    stdin_open: true
    tty: true

  teststudio-lite-frontend:
    build:
      context: teststudio-lite-frontend
    container_name: teststudio-lite-frontend
    volumes:
      - ./teststudio-lite-frontend/src:/app
      - node_modules_teststudio-lite:/app/node_modules
    ports:
      - '4210:4200'

volumes:
  dbdata:
    driver: local
  node_modules_teststudio-lite:
    driver: local
